export interface Office {
    id: number;             // Office ID in the system
    name: string;           // Office name
    externalId: string;    // External unique identifier
    parentId: number;      // Parent office ID
    hierarchy: string;     // Office hierarchy, generated by the system
    dateFormat: string;    // Date format, for example, "dd MMMM yyyy"
    locale: string;        // Locale, for example, "en"
    openingDate: string;   // Opening date, format "YYYY-MM-DD"
}